/**
 * Synapse Backup & Factory Reset Kit Generator.
 *
 * Synapse has no backup or reset Admin API. A full homeserver backup consists of:
 * - the PostgreSQL (or SQLite) database
 * - the media store directory
 * - homeserver.yaml and the signing key
 *
 * These live on the homeserver host, so this module generates ready-to-run
 * shell scripts the administrator deploys there — the same PREPARATION-tool
 * approach as server-prep.ts. The dashboard never touches the Synapse
 * database or filesystem directly.
 *
 * Backup guidance follows the official documentation:
 * https://element-hq.github.io/synapse/latest/usage/administration/backups.html
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface BackupConfig {
  serverName: string;
  deployment: "docker" | "native";

  // PostgreSQL connection (docker: container name; native: host/port)
  postgresContainer?: string;
  postgresHost?: string;
  postgresPort?: number;
  postgresDb: string;
  postgresUser: string;

  configPath: string; // directory containing homeserver.yaml + signing key
  mediaStorePath: string;
  backupDir: string;

  includeMedia: boolean;
  retentionDays: number;
  cronSchedule: string; // e.g. "0 3 * * *"
}

export interface BackupKit {
  backupScript: string;
  restoreScript: string;
  cronLine: string;
  checklist: string[];
}

export interface ResetScriptConfig {
  serverName: string;
  deployment: "docker" | "native";
  postgresContainer?: string;
  postgresHost?: string;
  postgresPort?: number;
  postgresDb: string;
  postgresUser: string;
  mediaStorePath: string;
  keepSigningKey: boolean;
  synapseService: string; // docker compose service name or systemd unit
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export function validateBackupConfig(config: BackupConfig): string[] {
  const issues: string[] = [];
  if (config.deployment === "docker" && !config.postgresContainer) {
    issues.push("postgresContainer is required for docker deployments");
  }
  if (config.deployment === "native" && !config.postgresHost) {
    issues.push("postgresHost is required for native deployments");
  }
  if (!config.backupDir.startsWith("/")) {
    issues.push("backupDir must be an absolute path");
  }
  if (!config.mediaStorePath.startsWith("/")) {
    issues.push("mediaStorePath must be an absolute path");
  }
  if (!config.configPath.startsWith("/")) {
    issues.push("configPath must be an absolute path");
  }
  if (!/^([\d*/,-]+\s+){4}[\d*/,-]+$/.test(config.cronSchedule.trim())) {
    issues.push("cronSchedule must be a 5-field cron expression (e.g. 0 3 * * *)");
  }
  return issues;
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

function pgDumpCommand(config: BackupConfig | ResetScriptConfig): string {
  if (config.deployment === "docker") {
    return `docker exec ${config.postgresContainer} pg_dump -U ${config.postgresUser} -d ${config.postgresDb}`;
  }
  return `pg_dump -h ${config.postgresHost} -p ${config.postgresPort ?? 5432} -U ${config.postgresUser} -d ${config.postgresDb}`;
}

export function generateBackupScript(config: BackupConfig): string {
  const mediaSection = config.includeMedia
    ? `
# --- Media store ---
tar -czf "\${BACKUP_PATH}/media_store.tar.gz" -C "$(dirname ${config.mediaStorePath})" "$(basename ${config.mediaStorePath})"
`
    : `
# Media store excluded (includeMedia=false). Media can be large; back it up
# separately if you need attachments/avatars restored.
`;

  return `#!/usr/bin/env bash
#
# Synapse backup for ${config.serverName}
# Generated by RiDDiX - Matrix Synapse Panel.
#
# A complete Synapse backup includes: database, media store, homeserver.yaml
# and the signing key. Ref:
# https://element-hq.github.io/synapse/latest/usage/administration/backups.html
#
set -euo pipefail

BACKUP_ROOT="${config.backupDir}"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_PATH="\${BACKUP_ROOT}/${config.serverName}-\${STAMP}"
mkdir -p "\${BACKUP_PATH}"

# --- Database ---
${pgDumpCommand(config)} | gzip > "\${BACKUP_PATH}/database.sql.gz"
${mediaSection}
# --- Config + signing key ---
tar -czf "\${BACKUP_PATH}/config.tar.gz" -C "$(dirname ${config.configPath})" "$(basename ${config.configPath})"

# --- Retention: delete backups older than ${config.retentionDays} days ---
find "\${BACKUP_ROOT}" -maxdepth 1 -type d -name "${config.serverName}-*" -mtime +${config.retentionDays} -exec rm -rf {} +

echo "Backup complete: \${BACKUP_PATH}"
`;
}

export function generateRestoreScript(config: BackupConfig): string {
  const restoreDb =
    config.deployment === "docker"
      ? `gunzip -c "\${BACKUP_PATH}/database.sql.gz" | docker exec -i ${config.postgresContainer} psql -U ${config.postgresUser} -d ${config.postgresDb}`
      : `gunzip -c "\${BACKUP_PATH}/database.sql.gz" | psql -h ${config.postgresHost} -p ${config.postgresPort ?? 5432} -U ${config.postgresUser} -d ${config.postgresDb}`;

  return `#!/usr/bin/env bash
#
# Synapse restore for ${config.serverName}
# Generated by RiDDiX - Matrix Synapse Panel.
#
# Usage: ./restore.sh <backup directory>
#
# IMPORTANT: Stop Synapse before restoring. Restore into an EMPTY database
# (drop and recreate it first). Never run a restored homeserver alongside
# the original — two servers with the same signing key and server_name
# corrupt federation state.
#
set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <backup directory>" >&2
  exit 1
fi
BACKUP_PATH="$1"

echo "Restoring ${config.serverName} from \${BACKUP_PATH}"
echo "Synapse must be STOPPED and the target database must be EMPTY."
read -r -p "Continue? [y/N] " REPLY
[ "\${REPLY}" = "y" ] || exit 1

# --- Database ---
${restoreDb}

# --- Media store ---
if [ -f "\${BACKUP_PATH}/media_store.tar.gz" ]; then
  tar -xzf "\${BACKUP_PATH}/media_store.tar.gz" -C "$(dirname ${config.mediaStorePath})"
fi

# --- Config + signing key ---
tar -xzf "\${BACKUP_PATH}/config.tar.gz" -C "$(dirname ${config.configPath})"

echo "Restore complete. Start Synapse and verify with the panel diagnostics."
`;
}

export function generateCronLine(config: BackupConfig): string {
  return `${config.cronSchedule.trim()} ${config.backupDir}/backup.sh >> ${config.backupDir}/backup.log 2>&1`;
}

export function generateBackupChecklist(config: BackupConfig): string[] {
  const checklist = [
    `Copy backup.sh to the homeserver host and place it in ${config.backupDir}/backup.sh, then chmod +x it.`,
    "Run backup.sh once manually and verify the backup directory contains database.sql.gz and config.tar.gz.",
    "Install the cron line with crontab -e (or a systemd timer).",
    "Store backups on a different machine or volume than the homeserver.",
    "Test the restore script against a throwaway database before you rely on it.",
    "The signing key inside config.tar.gz is secret — protect backup files accordingly.",
  ];
  if (!config.includeMedia) {
    checklist.push("Media store is NOT included in this kit — attachments and avatars will be lost unless backed up separately.");
  }
  if (config.deployment === "native") {
    checklist.push("pg_dump prompts for a password unless you configure ~/.pgpass for the postgres user.");
  }
  return checklist;
}

export function generateBackupKit(config: BackupConfig): BackupKit {
  return {
    backupScript: generateBackupScript(config),
    restoreScript: generateRestoreScript(config),
    cronLine: generateCronLine(config),
    checklist: generateBackupChecklist(config),
  };
}

/**
 * Generate a host-level factory reset script: stops Synapse, drops and
 * recreates the database, wipes the media store, optionally keeps the
 * signing key, and starts Synapse again.
 *
 * This is destructive and cannot be performed via the Admin API — it must
 * run on the homeserver host.
 */
export function generateFactoryResetScript(config: ResetScriptConfig): string {
  const stopCmd =
    config.deployment === "docker"
      ? `docker compose stop ${config.synapseService}`
      : `systemctl stop ${config.synapseService}`;
  const startCmd =
    config.deployment === "docker"
      ? `docker compose start ${config.synapseService}`
      : `systemctl start ${config.synapseService}`;
  const dropDb =
    config.deployment === "docker"
      ? `docker exec ${config.postgresContainer} psql -U ${config.postgresUser} -d postgres -c "DROP DATABASE IF EXISTS ${config.postgresDb};"
docker exec ${config.postgresContainer} psql -U ${config.postgresUser} -d postgres -c "CREATE DATABASE ${config.postgresDb} ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE=template0 OWNER ${config.postgresUser};"`
      : `psql -h ${config.postgresHost} -p ${config.postgresPort ?? 5432} -U ${config.postgresUser} -d postgres -c "DROP DATABASE IF EXISTS ${config.postgresDb};"
psql -h ${config.postgresHost} -p ${config.postgresPort ?? 5432} -U ${config.postgresUser} -d postgres -c "CREATE DATABASE ${config.postgresDb} ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE=template0 OWNER ${config.postgresUser};"`;

  const signingKeyNote = config.keepSigningKey
    ? "# Signing key is kept (config directory is not touched)."
    : `# WARNING: keepSigningKey=false — delete the old signing key manually from
# your config directory before starting Synapse, and expect remote servers
# to distrust the new key for cached key-validity periods.`;

  return `#!/usr/bin/env bash
#
# FACTORY RESET for ${config.serverName}
# Generated by RiDDiX - Matrix Synapse Panel.
#
# This DESTROYS the entire homeserver state: all users, rooms, messages and
# media. There is no undo. Take a backup first.
#
# FEDERATION WARNING: if this server has federated, remote homeservers have
# cached its events, device keys and signing key. Wiping the database while
# keeping the same server_name will cause federation problems (rejected
# events, undecryptable messages, stale device lists). The official
# recommendation is to use a NEW server_name after a database wipe:
# https://element-hq.github.io/synapse/latest/usage/administration/admin_faq.html
#
set -euo pipefail

echo "This will PERMANENTLY ERASE all data of ${config.serverName}."
read -r -p "Type the server name to confirm: " REPLY
[ "\${REPLY}" = "${config.serverName}" ] || { echo "Confirmation mismatch, aborting."; exit 1; }

# --- Stop Synapse ---
${stopCmd}

# --- Drop and recreate the database ---
${dropDb}

# --- Wipe media store ---
rm -rf ${config.mediaStorePath}/*

${signingKeyNote}

# --- Start Synapse (it recreates its schema on first run) ---
${startCmd}

echo "Factory reset complete. Re-run the panel's Admin Login to obtain a new admin token."
`;
}
